<?php include("./includes/breadcrumb.php"); ?>

<div class="titulos">Términos y condiciones</div>
<div class="container text-white">
  <p> Estos Términos de Uso (los "Términos de Uso") rigen el uso de (incluido el acceso a) el sitio web G8.com.ar operado por G8 SA, Capital Federal Buenos Aires. Argentina (en adelante, "G8, SA", "G8" o "nosotros") incluido el contenido disponible a través de este sitio web (el "Sitio Web").</p>
  <h2>OBJETIVO Y ACEPTACIÓN</h2>
  <p>Cualquier persona que acceda al Sitio Web ("usted") por este medio acepta estos Términos de Uso vigentes en el momento de su visita al Sitio Web, y acepta cumplir con dichos Términos de Uso. Estos Términos de Uso pueden variar de vez en cuando, y su uso de este Sitio Web está sujeto a los Términos de Uso vigentes a la fecha de su uso del Sitio Web. Por favor revise estos Términos de Uso regularmente para asegurarse de que los acepta. Si no está de acuerdo con ellos, absténgase de utilizar el Sitio Web.</p>
  <p>El contenido que ponemos a su disposición a través del Sitio Web (el "Contenido") puede estar sujeto a condiciones especiales ("condiciones especiales") que usted acepta cada vez que accede a dicho Contenido. En caso de conflicto o inconsistencia entre estos Términos de Uso y las condiciones especiales, las condiciones especiales prevalecerán sobre estos Términos de Uso. Cada vez que accede al Sitio Web y su Contenido, acepta estos Términos de Uso y las condiciones especiales aplicables a ese Contenido.</p>
  <p>El Sitio web no constituye ni pretende constituir una fuente de asesoramiento o un medio para establecer una relación comercial de ningún tipo entre usted y nosotros.</p>
  <p>El acceso al Sitio Web está permitido temporalmente, y nos reservamos el derecho de retirar o modificar el Contenido que proporcionamos en el Sitio Web sin previo aviso. De vez en cuando, podemos restringir el acceso a algunas partes del Sitio Web o al Sitio Web completo.</p>
  <p>No tenemos la obligación de hacer que el Sitio Web esté disponible, y no seremos responsables si, por algún motivo, el Sitio Web no está disponible, total o parcialmente, en cualquier momento o por cualquier período.</p>
  <h2>USO DEL SITIO WEB</h2>
  <p>Usted reconoce y acepta voluntaria y expresamente que su uso del Sitio Web se realiza bajo su única y exclusiva responsabilidad.</p>
  <p>Usted es responsable de hacer todos los arreglos necesarios para que tenga acceso al Sitio Web. También es responsable de garantizar que todas las personas que accedan al Sitio Web a través de su conexión a Internet conozcan estos Términos de Uso y las condiciones especiales aplicables, y cumplan con ellas.</p>
  <p>Si elige, o se le proporciona, un código de identificación de usuario, contraseña o cualquier otra información como parte de nuestros procedimientos de seguridad, debe tratar dicha información como confidencial y no debe divulgarla a terceros. Tenemos el derecho de deshabilitar cualquier código de identificación de usuario o contraseña, ya sea que usted haya elegido o asignado, en cualquier momento, si, en nuestra opinión, no cumple con alguna de las disposiciones de estos Términos de Uso.</p>
  <p>Al acceder al Sitio Web, acepta que no realizará ningún acto que pueda dañar nuestra imagen, intereses o derechos o los de cualquiera de nuestros afiliados ("compañías asociadas de G8"), o que pueda dañar, inutilizar o sobrecargar el Sitio Web, o eso puede impedir, de cualquier manera, el uso normal del Sitio Web por parte de otros visitantes.</p>
  <p>Implementamos medidas de seguridad razonables que son adecuadas para detectar la existencia de virus. Sin embargo, debe tener en cuenta que las medidas de seguridad existentes para los sistemas informáticos en Internet no son totalmente confiables y que, por lo tanto, no podemos garantizar la no existencia de virus o cualquier otro elemento que pueda causar alteraciones en sus sistemas informáticos (hardware y software), a sus datos y archivos contenidos en sus sistemas.</p>
  <h2>CONTENIDO</h2>
  <p>No tendremos el deber de verificar la exactitud del Contenido y no garantizamos la utilidad, precisión, integridad o relevancia del Contenido y/o que dicho Contenido esté actualizado. Excluimos expresamente cualquier y toda responsabilidad por errores u omisiones con respecto al Contenido y al Sitio Web, salvo en el caso de que dicha responsabilidad se deba a nuestro fraude o tergiversación fraudulenta o cualquier muerte o lesión personal que surja debido a nuestra negligencia.</p>
  <p>La inclusión del Contenido en el Sitio Web no constituye en modo alguno la provisión de servicios de personal o cualquier otro tipo de servicios. G8 y las compañías asociadas excluyen expresamente cualquier y todo tipo de responsabilidad por decisiones tomadas por usted con base en el Contenido.</p>
  <h2>NINGUNA OFERTA O SOLICITUD DE COMPRA</h2>
  La información proporcionada en el Sitio Web mediante consultas o preguntas en los formularios dispuestos para tal fin, no constituyen una oferta o solicitud de compra o disposición de transacciones o transacciones en cualquier valor de G8.
  <h2>DERECHOS DE PROPIEDAD INTELECTUAL</h2>
  <p>Todo el contenido del Sitio Web es de nuestra propiedad o está autorizado para su uso. Todo lo que vea o lea en el Sitio Web (como imágenes, fotografías, ilustraciones, textos, videoclips y otros materiales) está protegido en todo el mundo por derechos de autor, diseño, marcas registradas y otras leyes de Propiedad Intelectual. Debe respetar en todo momento todos los derechos de Propiedad Intelectual en el Sitio Web y el Contenido, ya sea de nuestra propiedad, de cualquiera de las compañías asociadas de G8 o de un tercero. No debe obtener ni intentar obtener ninguno de los Contenidos por medios o procedimientos que no sean los que el Sitio Web le ha puesto a su disposición.</p>
  <p>En ningún caso estos Términos de Uso o su uso del Sitio Web le otorgarán ningún derecho de Propiedad Intelectual en el Sitio Web o el Contenido, aparte de los establecidos en este documento o en las condiciones especiales. Por lo tanto, está expresamente prohibido realizar cualquier reproducción, transformación, distribución o comunicación pública de, o poner a disposición, extraer, reutilizar, reenviar o de cualquier otra forma, usar, por cualquier medio o procedimiento, cualquier parte del Sitio Web o el Contenido, a excepción de lo permitido por estos Términos de Uso o cualquiera de las condiciones especiales relevantes, o cuando lo permita la ley aplicable, o cuando el titular de los derechos relevantes haya otorgado una autorización explícita.</p>
  <h2>ENLACES A OTROS SITIOS</h2>
  Los enlaces a otros sitios web operados por terceros no afiliados a nosotros pueden indicarse en el Sitio Web. La inclusión de cualquier enlace a dichos sitios de terceros no implica la aprobación por nuestra parte de dichos sitios, y no aceptamos ninguna responsabilidad por los sitios web de terceros vinculados a/o desde este Sitio Web. No hemos revisado todos los sitios vinculados al Sitio Web y no somos responsables por el contenido o la precisión de las páginas externas o cualquier otro sitio vinculado al Sitio Web. Seguir cualquier enlace a cualquier otra página fuera del sitio o sitio de terceros es bajo su propio riesgo.
  <h2>INFORMACIÓN PERSONAL</h2>
  La recopilación y el uso de su Información Personal se rigen por nuestra Política de Privacidad, que está incorporada en estos Términos de Uso y se puede acceder aquí: <a href="?p=privacidad">www.g8.com.ar/privacidad</a>.
  <h2>LIMITACIONES DE RESPONSABILIDAD</h2>
  En la medida en que lo permita la ley aplicable, no garantizamos ni representamos que el Sitio Web y/o el Contenido sean precisos, completos, sin errores o confiables, o que el uso del Sitio Web y/o el Contenido no infrinja los derechos de terceros. En la medida en que lo permita la ley aplicable, no garantizamos ni representamos que los aspectos funcionales del Sitio Web y/o el Contenido estén libres de errores o que los servidores que lo ponen a disposición estén libres de virus u otros componentes dañinos. El uso del Sitio Web y/o el contenido está bajo su responsabilidad, y todo lo que se incluye en el Sitio Web se le proporciona "TAL CUAL" Y "COMO ESTÁ DISPONIBLE" SIN GARANTÍA DE NINGÚN TIPO, YA SEA EXPRESA O IMPLÍCITA. En la medida en que lo permita la ley aplicable, no seremos responsables de ninguna pérdida que surja de o en conexión con el uso del Sitio Web o el Contenido, ya sea directa o indirectamente, incidental, consecuencial o de otro tipo. Por ejemplo, renunciamos a cualquier y toda responsabilidad por pérdida de uso, interrupción del negocio, pérdida de beneficios o pérdida de datos, independientemente de la forma de acción.
  <h2>LEY APLICABLE Y JURISDICCIÓN</h2>
  Estos Términos de Uso y todas las cuestiones relacionadas con este Sitio Web y su contenido se rigen por la legislación argentina y estarán sujetos a la jurisdicción exclusiva de los tribunales ordinarios de la Ciudad Autónoma de Buenos Aires, Argentina.
  <h2>CAMBIOS EN NUESTROS TÉRMINOS DE USO</h2>
  <p>G8 se reserva el derecho de cambiar o enmendar los Términos de Uso de vez en cuando a su entera discreción, según lo permita la ley aplicable.</p>
  <p>Estos Términos de Uso pueden variar de vez en cuando y su uso de este Sitio Web está sujeto a los términos vigentes en ese momento cada vez que acceda al Sitio Web y su contenido. Consulte estos Términos de Uso con regularidad para asegurarse de que está familiarizado con ellos.</p>
  <h2>INFORMACIÓN DE CONTACTO</h2>
  Si tiene alguna pregunta sobre estos Términos de Uso, comuníquese con info@g8.com.ar o por correo postal a la atención del Departamento Legal en Argentina:
  <ul>
    <li>Alejandro Villafañe</li>
    <li>G8, S.A.</li>
    <li>Monroe 123, Ciudad Autonoma Buenos Aires, Argentina</li>
  </ul>
  Según lo permitido por la ley aplicable, puede comunicarse con su autoridad local de protección de datos si tiene alguna pregunta.
  <h2>ÚLTIMA ACTUALIZACIÓN DE LOS PRESENTES TÉRMINOS DE USO</h2>
  Fecha: 09 de Septiembre de 2019.

</div>
</div>